// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module ascon_reg_top (
  input clk_i,
  input rst_ni,
  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o,
  // To HW
  output ascon_reg_pkg::ascon_reg2hw_t reg2hw, // Write
  input  ascon_reg_pkg::ascon_hw2reg_t hw2reg, // Read

  // Integrity check errors
  output logic intg_err_o,

  // Config
  input devmode_i // If 1, explicit error return for unmapped register access
);

  import ascon_reg_pkg::* ;

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // incoming payload check
  logic intg_err;
  tlul_cmd_intg_chk u_chk (
    .tl_i(tl_i),
    .err_o(intg_err)
  );

  // also check for spurious write enables
  logic reg_we_err;
  logic [14:0] reg_we_check;
  prim_reg_we_check #(
    .OneHotWidth(15)
  ) u_prim_reg_we_check (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .oh_i  (reg_we_check),
    .en_i  (reg_we && !addrmiss),
    .err_o (reg_we_err)
  );

  logic err_q;
  always_ff @(posedge clk_i or negedge rst_ni) begin
    if (!rst_ni) begin
      err_q <= '0;
    end else if (intg_err || reg_we_err) begin
      err_q <= 1'b1;
    end
  end

  // integrity error output is permanent and should be used for alert generation
  // register errors are transactional
  assign intg_err_o = err_q | intg_err | reg_we_err;

  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(1),
    .EnableDataIntgGen(1)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = (devmode_i & addrmiss) | wr_err | intg_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic key_0_we;
  logic [31:0] key_0_wd;
  logic key_1_we;
  logic [31:0] key_1_wd;
  logic key_2_we;
  logic [31:0] key_2_wd;
  logic key_3_we;
  logic [31:0] key_3_wd;
  logic data_in_0_we;
  logic [31:0] data_in_0_wd;
  logic data_in_1_we;
  logic [31:0] data_in_1_wd;
  logic data_in_2_we;
  logic [31:0] data_in_2_wd;
  logic data_in_3_we;
  logic [31:0] data_in_3_wd;
  logic data_out_0_re;
  logic [31:0] data_out_0_qs;
  logic data_out_1_re;
  logic [31:0] data_out_1_qs;
  logic data_out_2_re;
  logic [31:0] data_out_2_qs;
  logic data_out_3_re;
  logic [31:0] data_out_3_qs;
  logic ctrl_we;
  logic ctrl_mode_qs;
  logic ctrl_mode_wd;
  logic ctrl_flavor_qs;
  logic ctrl_flavor_wd;
  logic ctrl_manual_start_trigger_qs;
  logic ctrl_manual_start_trigger_wd;
  logic ctrl_force_data_overwrite_qs;
  logic ctrl_force_data_overwrite_wd;
  logic trigger_we;
  logic trigger_qs;
  logic trigger_wd;
  logic status_idle_qs;
  logic status_stall_qs;
  logic status_output_valid_qs;
  logic status_input_ready_qs;

  // Register instances
  // Subregister 0 of Multireg key
  // R[key_0]: V(False)
  logic key_0_qe;
  logic [0:0] key_0_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_key0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&key_0_flds_we),
    .q_o(key_0_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_key_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (key_0_we),
    .wd     (key_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (key_0_flds_we[0]),
    .q      (reg2hw.key[0].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.key[0].qe = key_0_qe;


  // Subregister 1 of Multireg key
  // R[key_1]: V(False)
  logic key_1_qe;
  logic [0:0] key_1_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_key1_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&key_1_flds_we),
    .q_o(key_1_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_key_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (key_1_we),
    .wd     (key_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (key_1_flds_we[0]),
    .q      (reg2hw.key[1].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.key[1].qe = key_1_qe;


  // Subregister 2 of Multireg key
  // R[key_2]: V(False)
  logic key_2_qe;
  logic [0:0] key_2_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_key2_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&key_2_flds_we),
    .q_o(key_2_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_key_2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (key_2_we),
    .wd     (key_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (key_2_flds_we[0]),
    .q      (reg2hw.key[2].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.key[2].qe = key_2_qe;


  // Subregister 3 of Multireg key
  // R[key_3]: V(False)
  logic key_3_qe;
  logic [0:0] key_3_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_key3_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&key_3_flds_we),
    .q_o(key_3_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_key_3 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (key_3_we),
    .wd     (key_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (key_3_flds_we[0]),
    .q      (reg2hw.key[3].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.key[3].qe = key_3_qe;


  // Subregister 0 of Multireg data_in
  // R[data_in_0]: V(False)
  logic data_in_0_qe;
  logic [0:0] data_in_0_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_data_in0_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&data_in_0_flds_we),
    .q_o(data_in_0_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_in_0 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_in_0_we),
    .wd     (data_in_0_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (data_in_0_flds_we[0]),
    .q      (reg2hw.data_in[0].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.data_in[0].qe = data_in_0_qe;


  // Subregister 1 of Multireg data_in
  // R[data_in_1]: V(False)
  logic data_in_1_qe;
  logic [0:0] data_in_1_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_data_in1_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&data_in_1_flds_we),
    .q_o(data_in_1_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_in_1 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_in_1_we),
    .wd     (data_in_1_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (data_in_1_flds_we[0]),
    .q      (reg2hw.data_in[1].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.data_in[1].qe = data_in_1_qe;


  // Subregister 2 of Multireg data_in
  // R[data_in_2]: V(False)
  logic data_in_2_qe;
  logic [0:0] data_in_2_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_data_in2_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&data_in_2_flds_we),
    .q_o(data_in_2_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_in_2 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_in_2_we),
    .wd     (data_in_2_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (data_in_2_flds_we[0]),
    .q      (reg2hw.data_in[2].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.data_in[2].qe = data_in_2_qe;


  // Subregister 3 of Multireg data_in
  // R[data_in_3]: V(False)
  logic data_in_3_qe;
  logic [0:0] data_in_3_flds_we;
  prim_flop #(
    .Width(1),
    .ResetValue(0)
  ) u_data_in3_qe (
    .clk_i(clk_i),
    .rst_ni(rst_ni),
    .d_i(&data_in_3_flds_we),
    .q_o(data_in_3_qe)
  );
  prim_subreg #(
    .DW      (32),
    .SwAccess(prim_subreg_pkg::SwAccessWO),
    .RESVAL  (32'h0),
    .Mubi    (1'b0)
  ) u_data_in_3 (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (data_in_3_we),
    .wd     (data_in_3_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (data_in_3_flds_we[0]),
    .q      (reg2hw.data_in[3].q),
    .ds     (),

    // to register interface (read)
    .qs     ()
  );
  assign reg2hw.data_in[3].qe = data_in_3_qe;


  // Subregister 0 of Multireg data_out
  // R[data_out_0]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_data_out_0 (
    .re     (data_out_0_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.data_out[0].d),
    .qre    (reg2hw.data_out[0].re),
    .qe     (),
    .q      (reg2hw.data_out[0].q),
    .ds     (),
    .qs     (data_out_0_qs)
  );


  // Subregister 1 of Multireg data_out
  // R[data_out_1]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_data_out_1 (
    .re     (data_out_1_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.data_out[1].d),
    .qre    (reg2hw.data_out[1].re),
    .qe     (),
    .q      (reg2hw.data_out[1].q),
    .ds     (),
    .qs     (data_out_1_qs)
  );


  // Subregister 2 of Multireg data_out
  // R[data_out_2]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_data_out_2 (
    .re     (data_out_2_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.data_out[2].d),
    .qre    (reg2hw.data_out[2].re),
    .qe     (),
    .q      (reg2hw.data_out[2].q),
    .ds     (),
    .qs     (data_out_2_qs)
  );


  // Subregister 3 of Multireg data_out
  // R[data_out_3]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_data_out_3 (
    .re     (data_out_3_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.data_out[3].d),
    .qre    (reg2hw.data_out[3].re),
    .qe     (),
    .q      (reg2hw.data_out[3].q),
    .ds     (),
    .qs     (data_out_3_qs)
  );


  // R[ctrl]: V(False)
  //   F[mode]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_mode (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_mode_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.mode.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_mode_qs)
  );

  //   F[flavor]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_flavor (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_flavor_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.flavor.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_flavor_qs)
  );

  //   F[manual_start_trigger]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_manual_start_trigger (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_manual_start_trigger_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.manual_start_trigger.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_manual_start_trigger_qs)
  );

  //   F[force_data_overwrite]: 3:3
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_ctrl_force_data_overwrite (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (ctrl_we),
    .wd     (ctrl_force_data_overwrite_wd),

    // from internal hardware
    .de     (1'b0),
    .d      ('0),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.ctrl.force_data_overwrite.q),
    .ds     (),

    // to register interface (read)
    .qs     (ctrl_force_data_overwrite_qs)
  );


  // R[trigger]: V(False)
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRW),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_trigger (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (trigger_we),
    .wd     (trigger_wd),

    // from internal hardware
    .de     (hw2reg.trigger.de),
    .d      (hw2reg.trigger.d),

    // to internal hardware
    .qe     (),
    .q      (reg2hw.trigger.q),
    .ds     (),

    // to register interface (read)
    .qs     (trigger_qs)
  );


  // R[status]: V(False)
  //   F[idle]: 0:0
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_status_idle (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.status.idle.de),
    .d      (hw2reg.status.idle.d),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (status_idle_qs)
  );

  //   F[stall]: 1:1
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_status_stall (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.status.stall.de),
    .d      (hw2reg.status.stall.d),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (status_stall_qs)
  );

  //   F[output_valid]: 2:2
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h0),
    .Mubi    (1'b0)
  ) u_status_output_valid (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.status.output_valid.de),
    .d      (hw2reg.status.output_valid.d),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (status_output_valid_qs)
  );

  //   F[input_ready]: 3:3
  prim_subreg #(
    .DW      (1),
    .SwAccess(prim_subreg_pkg::SwAccessRO),
    .RESVAL  (1'h1),
    .Mubi    (1'b0)
  ) u_status_input_ready (
    .clk_i   (clk_i),
    .rst_ni  (rst_ni),

    // from register interface
    .we     (1'b0),
    .wd     ('0),

    // from internal hardware
    .de     (hw2reg.status.input_ready.de),
    .d      (hw2reg.status.input_ready.d),

    // to internal hardware
    .qe     (),
    .q      (),
    .ds     (),

    // to register interface (read)
    .qs     (status_input_ready_qs)
  );



  logic [14:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == ASCON_KEY_0_OFFSET);
    addr_hit[ 1] = (reg_addr == ASCON_KEY_1_OFFSET);
    addr_hit[ 2] = (reg_addr == ASCON_KEY_2_OFFSET);
    addr_hit[ 3] = (reg_addr == ASCON_KEY_3_OFFSET);
    addr_hit[ 4] = (reg_addr == ASCON_DATA_IN_0_OFFSET);
    addr_hit[ 5] = (reg_addr == ASCON_DATA_IN_1_OFFSET);
    addr_hit[ 6] = (reg_addr == ASCON_DATA_IN_2_OFFSET);
    addr_hit[ 7] = (reg_addr == ASCON_DATA_IN_3_OFFSET);
    addr_hit[ 8] = (reg_addr == ASCON_DATA_OUT_0_OFFSET);
    addr_hit[ 9] = (reg_addr == ASCON_DATA_OUT_1_OFFSET);
    addr_hit[10] = (reg_addr == ASCON_DATA_OUT_2_OFFSET);
    addr_hit[11] = (reg_addr == ASCON_DATA_OUT_3_OFFSET);
    addr_hit[12] = (reg_addr == ASCON_CTRL_OFFSET);
    addr_hit[13] = (reg_addr == ASCON_TRIGGER_OFFSET);
    addr_hit[14] = (reg_addr == ASCON_STATUS_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(ASCON_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(ASCON_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(ASCON_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(ASCON_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(ASCON_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(ASCON_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(ASCON_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(ASCON_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(ASCON_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(ASCON_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(ASCON_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(ASCON_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(ASCON_PERMIT[12] & ~reg_be))) |
               (addr_hit[13] & (|(ASCON_PERMIT[13] & ~reg_be))) |
               (addr_hit[14] & (|(ASCON_PERMIT[14] & ~reg_be)))));
  end

  // Generate write-enables
  assign key_0_we = addr_hit[0] & reg_we & !reg_error;

  assign key_0_wd = reg_wdata[31:0];
  assign key_1_we = addr_hit[1] & reg_we & !reg_error;

  assign key_1_wd = reg_wdata[31:0];
  assign key_2_we = addr_hit[2] & reg_we & !reg_error;

  assign key_2_wd = reg_wdata[31:0];
  assign key_3_we = addr_hit[3] & reg_we & !reg_error;

  assign key_3_wd = reg_wdata[31:0];
  assign data_in_0_we = addr_hit[4] & reg_we & !reg_error;

  assign data_in_0_wd = reg_wdata[31:0];
  assign data_in_1_we = addr_hit[5] & reg_we & !reg_error;

  assign data_in_1_wd = reg_wdata[31:0];
  assign data_in_2_we = addr_hit[6] & reg_we & !reg_error;

  assign data_in_2_wd = reg_wdata[31:0];
  assign data_in_3_we = addr_hit[7] & reg_we & !reg_error;

  assign data_in_3_wd = reg_wdata[31:0];
  assign data_out_0_re = addr_hit[8] & reg_re & !reg_error;
  assign data_out_1_re = addr_hit[9] & reg_re & !reg_error;
  assign data_out_2_re = addr_hit[10] & reg_re & !reg_error;
  assign data_out_3_re = addr_hit[11] & reg_re & !reg_error;
  assign ctrl_we = addr_hit[12] & reg_we & !reg_error;

  assign ctrl_mode_wd = reg_wdata[0];

  assign ctrl_flavor_wd = reg_wdata[1];

  assign ctrl_manual_start_trigger_wd = reg_wdata[2];

  assign ctrl_force_data_overwrite_wd = reg_wdata[3];
  assign trigger_we = addr_hit[13] & reg_we & !reg_error;

  assign trigger_wd = reg_wdata[0];

  // Assign write-enables to checker logic vector.
  always_comb begin
    reg_we_check = '0;
    reg_we_check[0] = key_0_we;
    reg_we_check[1] = key_1_we;
    reg_we_check[2] = key_2_we;
    reg_we_check[3] = key_3_we;
    reg_we_check[4] = data_in_0_we;
    reg_we_check[5] = data_in_1_we;
    reg_we_check[6] = data_in_2_we;
    reg_we_check[7] = data_in_3_we;
    reg_we_check[8] = 1'b0;
    reg_we_check[9] = 1'b0;
    reg_we_check[10] = 1'b0;
    reg_we_check[11] = 1'b0;
    reg_we_check[12] = ctrl_we;
    reg_we_check[13] = trigger_we;
    reg_we_check[14] = 1'b0;
  end

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[2]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[4]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[5]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[6]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[7]: begin
        reg_rdata_next[31:0] = '0;
      end

      addr_hit[8]: begin
        reg_rdata_next[31:0] = data_out_0_qs;
      end

      addr_hit[9]: begin
        reg_rdata_next[31:0] = data_out_1_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = data_out_2_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = data_out_3_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[0] = ctrl_mode_qs;
        reg_rdata_next[1] = ctrl_flavor_qs;
        reg_rdata_next[2] = ctrl_manual_start_trigger_qs;
        reg_rdata_next[3] = ctrl_force_data_overwrite_qs;
      end

      addr_hit[13]: begin
        reg_rdata_next[0] = trigger_qs;
      end

      addr_hit[14]: begin
        reg_rdata_next[0] = status_idle_qs;
        reg_rdata_next[1] = status_stall_qs;
        reg_rdata_next[2] = status_output_valid_qs;
        reg_rdata_next[3] = status_input_ready_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
